// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBodwyV7a-iXKufmNjMzYZvot11muc_ig',
    appId: '1:996698290424:web:a865726e6b79e6b48f630d',
    messagingSenderId: '996698290424',
    projectId: 'aviapoint-7f329',
    authDomain: 'aviapoint-7f329.firebaseapp.com',
    storageBucket: 'aviapoint-7f329.firebasestorage.app',
    measurementId: 'G-4HS9RB0WX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFKanuKl38irph1H91Vzmev3-OHX58T8E',
    appId: '1:996698290424:android:616d982db9d415b18f630d',
    messagingSenderId: '996698290424',
    projectId: 'aviapoint-7f329',
    storageBucket: 'aviapoint-7f329.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHYlMPfcTx8JU8uTcQSYk258fkIBmvgTg',
    appId: '1:996698290424:ios:7371b95d228e017d8f630d',
    messagingSenderId: '996698290424',
    projectId: 'aviapoint-7f329',
    storageBucket: 'aviapoint-7f329.firebasestorage.app',
    iosBundleId: 'ru.dartflutterworld.ch',
  );
}
