// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfxnnGLqc5c2F0yFu421Jh9YM_Ed2Dj5I',
    appId: '1:591230040091:web:0a26e42135d38dce37a0be',
    messagingSenderId: '591230040091',
    projectId: 'aviapoint',
    authDomain: 'aviapoint.firebaseapp.com',
    storageBucket: 'aviapoint.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcT6JeUkM6owRc6WsvVsZ1CyXO8MQvLyE',
    appId: '1:591230040091:android:97028d2ed7bef3de37a0be',
    messagingSenderId: '591230040091',
    projectId: 'aviapoint',
    storageBucket: 'aviapoint.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6X7dz4IH_4n06IZBB8JDEfGv9Fpr2bdA',
    appId: '1:591230040091:ios:4d5e15696d584a9037a0be',
    messagingSenderId: '591230040091',
    projectId: 'aviapoint',
    storageBucket: 'aviapoint.firebasestorage.app',
    iosBundleId: 'ru.dartflutter.aviapoint',
  );

}