#!/bin/bash

# Скрипт для очистки миграций - оставить только базовую синхронизацию
# Использование: выполните в проекте aviapoint_server локально

echo "🧹 Очистка миграций - оставить только базовую синхронизацию..."
echo ""
echo "ВАЖНО: Выполните это в ЛОКАЛЬНОМ проекте aviapoint_server!"
echo ""
echo "cd ~/Projects/aviapoint_server  # или путь к вашему локальному проекту"
echo ""
echo "# 1. Посмотреть все миграции"
echo "ls -la migrations/*.sql | wc -l"
echo "ls migrations/*.sql"
echo ""
echo "# 2. Найти базовую миграцию синхронизации (скорее всего 072_sync_all_tables_and_fields.sql)"
echo "ls migrations/072*.sql migrations/*sync*.sql 2>/dev/null"
echo ""
echo "# 3. Переместить миграции с контентом в папку old_migrations (для истории)"
echo "mkdir -p migrations/old_migrations"
echo "mv migrations/insert_aircraft_catalog_data*.sql migrations/old_migrations/ 2>/dev/null"
echo ""
echo "# 4. Удалить или отключить другие проблемные миграции"
echo "# Удалить миграции, которые добавляют контент, а не структуру:"
echo "# - insert_aircraft_catalog_data*.sql"
echo "# - clear_all_flights_data.sql (если не нужна)"
echo "# - другие insert/update миграции с данными"
echo ""
echo "# 5. Оставить только:"
echo "# - Базовую миграцию синхронизации (072_sync_all_tables_and_fields.sql)"
echo "# - Миграции создания таблиц (create_*.sql)"
echo "# - Миграции изменения структуры (add_*, alter_*, rename_*)"
echo ""
echo "# 6. Проверить, что базовая миграция исправлена (нет проблем с SELECT, is_active)"
echo "grep -n 'SELECT.*FROM news' migrations/072_sync_all_tables_and_fields.sql | grep -v 'INTO' | grep -v 'EXISTS'"
echo "grep -n 'is_active' migrations/072_sync_all_tables_and_fields.sql | grep -i index"
echo ""
echo "# 7. Закоммитить изменения"
echo "git add migrations/"
echo "git commit -m 'Cleanup: удаление миграций с контентом, оставлена только базовая синхронизация'"
echo "git push"
echo ""
echo "# 8. На сервере:"
echo "ssh root@83.166.246.205"
echo "cd /home/aviapoint_server"
echo "git pull"
echo "docker-compose -f docker-compose.prod.yaml restart aviapoint-server"
echo ""
