#!/bin/bash

# Скрипт для удаления всех созданий индексов на несуществующее поле is_active
# Использование: выполните на сервере

echo "🗑️  Удаление всех созданий индексов на is_active..."
echo ""
echo "Выполните на сервере:"
echo ""
echo "cd /home/aviapoint_server"
echo ""
echo "# 1. Удалить все создания индексов на is_active из активных миграций"
echo "# (не трогаем sync_schema и test_migration - это старые файлы)"
echo ""
echo "# Удалить из миграции 072:"
echo "sed -i '/CREATE INDEX IF NOT EXISTS idx_subscriptions_is_active ON subscriptions(is_active);/d' migrations/072_sync_all_tables_and_fields.sql"
echo "sed -i '/CREATE INDEX IF NOT EXISTS idx_aircraft_market_is_active ON aircraft_market(is_active);/d' migrations/072_sync_all_tables_and_fields.sql"
echo ""
echo "# Удалить из create_aircraft_catalog_tables.sql:"
echo "sed -i '/CREATE INDEX IF NOT EXISTS idx_manufacturers_active ON manufacturers(is_active);/d' migrations/create_aircraft_catalog_tables.sql"
echo "sed -i '/CREATE INDEX IF NOT EXISTS idx_aircraft_models_active ON aircraft_models(is_active);/d' migrations/create_aircraft_catalog_tables.sql"
echo ""
echo "# Удалить из create_aircraft_types_table.sql:"
echo "sed -i '/CREATE INDEX IF NOT EXISTS idx_aircraft_types_active ON aircraft_types(is_active);/d' migrations/create_aircraft_types_table.sql"
echo ""
echo "# Удалить из create_airports_table.sql:"
echo "sed -i '/CREATE INDEX IF NOT EXISTS idx_airports_is_active ON airports(is_active);/d' migrations/create_airports_table.sql"
echo ""
echo "# Удалить из create_market_products_table.sql:"
echo "sed -i '/CREATE INDEX IF NOT EXISTS idx_market_products_is_active ON market_products(is_active);/d' migrations/create_market_products_table.sql"
echo ""
echo "# Удалить из create_subscriptions_table.sql:"
echo "sed -i '/CREATE INDEX IF NOT EXISTS idx_subscriptions_is_active ON subscriptions(is_active);/d' migrations/create_subscriptions_table.sql"
echo ""
echo "# Удалить из recreate_airports_table_aopa.sql:"
echo "sed -i '/CREATE INDEX idx_airports_is_active ON airports(is_active);/d' migrations/recreate_airports_table_aopa.sql"
echo ""
echo "# 2. Проверить результат"
echo "grep -rn 'CREATE INDEX.*is_active' migrations/*.sql | grep -v sync_schema | grep -v test_migration"
echo ""
