#!/bin/bash

# Скрипт для проверки применения исправлений
# Использование: выполните на сервере

echo "✅ Проверка применения исправлений..."
echo ""
echo "Выполните на сервере:"
echo ""
echo "cd /home/aviapoint_server"
echo ""
echo "# 1. Проверить, что max_id_val вычисляется ДО использования в миграции 071"
echo "grep -B 2 -A 10 'IF duplicate_count > 0 THEN' migrations/071_add_content_and_images_to_news.sql | head -15"
echo ""
echo "# 2. Проверить, что дублирующее вычисление удалено"
echo "grep -n 'INTO max_id_val' migrations/071_add_content_and_images_to_news.sql"
echo ""
echo "# 3. Проверить миграцию 072 - там тоже может быть проблема с порядком"
echo "grep -B 5 -A 10 'IF duplicate_count > 0 THEN' migrations/072_sync_all_tables_and_fields.sql | head -15"
echo "grep -n 'INTO max_id_val' migrations/072_sync_all_tables_and_fields.sql"
echo ""
echo "# 4. Проверить, что нет больше проблемных SELECT"
echo "grep -n '(SELECT COALESCE(MAX(id), 0) FROM news)' migrations/071_add_content_and_images_to_news.sql"
echo "grep -n '(SELECT COALESCE(MAX(id), 0) FROM news)' migrations/072_sync_all_tables_and_fields.sql"
echo ""
echo "# 5. Сохранить изменения"
echo "git add migrations/"
echo "git commit -m 'Fix: исправление порядка вычисления max_id_val в миграциях'"
echo ""
echo "# 6. Перезапустить бэкенд"
echo "docker-compose -f docker-compose.prod.yaml restart aviapoint-server"
echo ""
echo "# 7. Проверить логи"
echo "docker-compose -f docker-compose.prod.yaml logs -f aviapoint-server | grep -i error"
echo ""
